# Numpy

Numpy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays.

#### Why Numpy?
Numpy is the core of scientific computing in Python. It provides a high-performance multidimensional array operation.
Numpy allow you to performe optimized operations on an vectorized array.

In comparison with list, where you must perform a certain operation on each element (usually through a loop), Numpy allow you to perform such operation on the entire array at once.

Numpy is written in C, which makes it very fast and eficient.

#### Numpy array
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [1]:
import numpy as np

a = np.array([1,2,3])               # Create an rank 1 array
print("array type:", type(a))
print("array shape:", a.shape)
print(a[0], a[1])


array type: <class 'numpy.ndarray'>
array shape: (3,)
1 2


In [2]:
b = np.array([[1,2,3],[4,5,6]])
print("array shape:", b.shape)
print(b[0,0], b[0,1], b[1,0])

array shape: (2, 3)
1 2 4


In [3]:
# create an array of zeros
a = np.zeros((2,2))
print("array of zeros:\n", a)
print()

# create an array of 1s
a = np.ones((1,2))
print("array of ones:\n", a)
print()

# creata an array of a constant
a = np.full((2,2), 7, dtype=int)  # here I specified the type to be an interger
print("array of constant:\n", a)
print()

array of zeros:
 [[0. 0.]
 [0. 0.]]

array of ones:
 [[1. 1.]]

array of constant:
 [[7 7]
 [7 7]]



In [4]:
# create an identity matrix
a = np.eye(3)
print("identity matrix :\n", a)
print()

a = np.random.random((2,2))
print("random array :\n", a)
print()

identity matrix :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

random array :
 [[0.27304899 0.36191915]
 [0.68203839 0.85547087]]



In [5]:
a = np.empty((2,3))
print("empty array :\n", a)  # Note that an empty array will have some random data inside
print()

empty array :
 [[0. 0. 0.]
 [0. 0. 0.]]



In [6]:
# Creating a 1D array of numbers from 10 to 30 in increments of 5
a = np.arange( 10, 30, 5 )
print("from 10 to 30 in increments of 5:", a)
print()

# Creating a 1D array of numbers from 0 to 2 in increments of 0.3
a= np.arange( 0, 2, 0.3 )
print("from 0 to 2 in increments of 0.3", a)
print()

# Creating a 1D array of 9 numbers equally spaced from 0 to 2 
a = np.linspace( 0, 2, 9 )
print("Array of 9 numbers equally spaced from 0 to 2", a)

from 10 to 30 in increments of 5: [10 15 20 25]

from 0 to 2 in increments of 0.3 [0.  0.3 0.6 0.9 1.2 1.5 1.8]

Array of 9 numbers equally spaced from 0 to 2 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


# Basic Arithmetic
In Numpy, arithmetic operators on arrays are always applied elementwise. A new array is filled and returned with the result.



In [7]:
# create 2 arrays a and b, and subtract b from a
a = np.array( [20,30,40,50] )
b = np.array( [0, 1, 2, 3] )
c = a - b
print(c)

[20 29 38 47]


In [8]:
# You can also perform scalar operations elementwise on the entire array
print(b)
c = b**2
print(c)

[0 1 2 3]
[0 1 4 9]


In [9]:
#You can also apply functions
print(a)
c = 10*np.sin(a)
print(c)

[20 30 40 50]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [10]:
#Operation between arrays are always applied elementwise
print(a)
print(b)
print("this is a * b:", a * b)

[20 30 40 50]
[0 1 2 3]
this is a * b: [  0  30  80 150]


In [11]:
# There are many quick and useful functions in numpy that you will use frequently like these
print(a)
print(a.max()) 
print(a.min()) 
print(a.sum()) 

[20 30 40 50]
50
20
140


In [12]:
# If you have a multi-dimensional array, use the "axis" parameter
d = np.arange(12).reshape(3,4)
print("multidimensional array:\n", d)
print()

print("sum of colums (axis0):\n", d.sum(axis=0),"\n")
print("sum of rows (axis1):\n", d.sum(axis=1),"\n")

multidimensional array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

sum of colums (axis0):
 [12 15 18 21] 

sum of rows (axis1):
 [ 6 22 38] 



In [13]:
# Transpose a matrix
print(d, "\n")

print(d.T,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] 



In [14]:
# convert a list to an np array

a_list = [1,2,3]
a_array = np.asarray(a_list)
print(type(a_list), type(a_array), a_array)

<class 'list'> <class 'numpy.ndarray'> [1 2 3]


# Array indexing and slicing

In [15]:
# NP arrays are indexed and sliced as any other iterable

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a[2])
print(a[2:5])
print(a[:8])
print(a[-1])

2
[2 3 4]
[0 1 2 3 4 5 6 7]
10


In [16]:
b = np.array([[ 0,  1,  2,  3],
     [10, 11, 12, 13],
     [20, 21, 22, 23],
     [30, 31, 32, 33],
[40, 41, 42, 43]])

print(b[2,3],"\n")
print(b[0:5, 1],"\n") #  each row in the second column of b --> [ 1, 11, 21, 31, 41]
print(b[:, 1],"\n")   #  same thing as above --> [ 1, 11, 21, 31, 41]
print(b[1:3, :],"\n") #  each column in the second and third row of b --> [[10, 11, 12, 13], [20, 21, 22, 23]]


23 

[ 1 11 21 31 41] 

[ 1 11 21 31 41] 

[[10 11 12 13]
 [20 21 22 23]] 



In [17]:
# Iteranting over an np matrix
# the outer loop is done in respect to the fisrt axis (the rows)
for row in b:
    print(row)



[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


### These are all the Numpy data types at your disposal

np.int64   # Signed 64-bit integer types

np.float32 # Standard double-precision floating point

np.complex # Complex numbers represented by 128 floats

np.bool    # Boolean type storing TRUE and FALSE values

np.object  # Python object type

np.string  # Fixed-length string type

np.unicode # Fixed-length unicode type


## Boolean operations in numpy arrays

In [18]:
a = np.array([1, 2, 3])
b = np.array([5, 4, 3])

# If we compare directly we get a boolean value for each element
print("check if each elemente of a is equal to b\n", a == b, "\n")

print("check if each elemente of a is less than or equal than 2\n", a <= 2, "\n")

check if each elemente of a is equal to b
 [False False  True] 

check if each elemente of a is less than or equal than 2
 [ True  True False] 



## Basic statistics with numpy arrays


In [19]:
a = np.array(
    [[3,7,5],
     [8,4,3],
     [2,4,9]])

# get the minimum value of axis 1 (rows)
print("Smallest value of each row:", np.amin(a,1))

# get the max value of axis 1 (rows)
print("largest value of each row:", np.amax(a,1),"\n")

## get the minimum value of axis 0 (columns)
print("Smallest value of each colum:", np.amin(a,0))

# Get largest value of the matrix
print("largest value of the matrix:", np.max(a))

Smallest value of each row: [3 3 2]
largest value of each row: [7 8 9] 

Smallest value of each colum: [2 4 3]
largest value of the matrix: 9


In [69]:
a = np.array(
    [[30,40,70],
     [80,20,10],
     [50,90,60]]) 

print(a,"\n")

print("median of the whole matrix:", np.median(a),"\n")
print("median of the rows:", np.median(a, 1),"\n")
print("median of the columns:", np.median(a, 0),"\n")


[[30 40 70]
 [80 20 10]
 [50 90 60]] 

median of the whole matrix: 50.0 

median of the rows: [ 40.  20.  60.] 

median of the columns: [ 50.  40.  60.] 



In [20]:
a = np.array(
    [[30,40,70],
     [80,20,10],
     [50,90,60]]) 

print(a,"\n")

print("mean of the whole matrix:", np.mean(a),"\n")
print("mean of the rows:", np.mean(a, 1),"\n")
print("mean of the columns:", np.mean(a, 0),"\n")

[[30 40 70]
 [80 20 10]
 [50 90 60]] 

mean of the whole matrix: 50.0 

mean of the rows: [46.66666667 36.66666667 66.66666667] 

mean of the columns: [53.33333333 50.         46.66666667] 



# Average
Weighted average is an average resulting from the multiplication of each component by a factor reflecting its importance. The numpy.average() function computes the weighted average of elements in an array according to their respective weight given in another array. The function can have an axis parameter. If the axis is not specified, the array is flattened.

Considering an array [1,2,3,4] and corresponding weights [4,3,2,1], the weighted average is calculated by adding the product of the corresponding elements and dividing the sum by the sum of weights.

Weighted average = (1 x 4 + 2 x 3 + 3 * 2 + 4 * 1)/(4+3+2+1)

In [21]:
a = np.array([1,2,3,4]) 
print("array average is:", np.average(a)) # same as mean if no weight is specified


# Weighted average
wts = np.array([4,3,2,1]) 
print("array average is:", np.average(a,weights = wts))



array average is: 2.5
array average is: 2.0


## Standard Deviation


In [22]:
# STD
print("Std of a:", np.std(a))

# Variance
print("Std of a:", np.var(a))

Std of a: 1.118033988749895
Std of a: 1.25
